version: '3'
services:
     app:
        container_name: 'fastapi'
        image: fastapi:latest
        ports:
           - 8000:80
        tty: true
        volumes:
          - "C:\\Projects\\Fastapi:/app"
        restart: unless-stopped
        command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80 --reload
