version: '3'
services:
     app:
        container_name: 'fastapi'
        image: ghcr.io/emon5122/fastapi:latest
        ports:
           - 80:8000
        tty: true
        volumes:
           - ./src:/app
        restart: unless-stopped
        command: uvicorn main:app --host 0.0.0.0 --reload
