
name: Docker CI

on:
  push:
    branches: [master]

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      -
       name: checkout
       uses: actions/checkout@v3
      -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v2
      -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2 
      -
       name: Docker Login
       uses: docker/login-action@v2
       with:
           registry: ghcr.io
           username: ${{ secrets.DOCKER_USER_NAME }}
           password: ${{secrets.DOCKER_IMG}}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/emon5122/fastapi
          # generate Docker tags based on the following events/attributes
          labels: |
            maintainer=Istiak Hassan Emon
            org.opencontainers.image.title=FastAPI
            org.opencontainers.image.description=Social Media APIs developed by FastAPI
            org.opencontainers.image.vendor=Nexis Limited
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
     
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
            context: .
            platforms: linux/amd64
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
                BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
                VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
                REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}


